version: '3.8'

networks:
  smca-network:
    driver: bridge

services:
  smca-frontend:
    build: ./client
    ports:
      - '5123:3000'
    container_name: smca-frontend-container
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    depends_on:
      - smca-mysql
      - smca-backend
    networks:
     - smca-network
    stdin_open: true
    tty: true

  smca-backend:
    build: ./server
    ports:
      - '5122:5122'
    container_name: smca-backend-container
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    depends_on:
      - smca-mysql
    networks:
      - smca-network
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_BACKEND_DOCKER_HOST}
      - MYSQL_ROOT_USERNAME=${MYSQL_ROOT_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_POOL_CONNECTION_LIMIT=${MYSQL_POOL_CONNECTION_LIMIT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    stdin_open: true
    tty: true
 
  smca-mysql:
    image: mysql:8.0.32
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    container_name: smca-mysql-container
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - SERVICE_NAME=smca-mysql
    networks:
      - smca-network
    volumes:
      - $HOME/database:/var/lib/mysql
    expose:
      - 3306
